import type { Metadata } from "next";
import { Jost, Libre_Caslon_Text } from "next/font/google";
import "./globals.css";
import OfferHeader from "@/components/header/OfferHeader";
import Header from "@/components/header/Header";
import Footer from "@/components/AiComponents/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import GetQuoteDialog from "@/components/Dialogs/AiDialogs/GetQuoteDialog";

const jostFont = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const libreCaslonFont = Libre_Caslon_Text({
  variable: "--libre-caslon-text",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jostFont.variable} ${libreCaslonFont.variable} antialiased mx-auto max-w-[1920px] max-sm:max-w-full`}
      >
        <ReduxProvider>
          <GetQuoteDialog />
          <OfferHeader />
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
